In [97]:
import json
import pandas as pd

pred=json.load(open('predictions.json'))

In [98]:
import collections
#pred_sorted=collections.OrderedDict(sorted(pred.items()))
submission_ex=pd.read_csv('submission_example.csv')

In [99]:
print(len(pred.keys()))

39

In [100]:
for i in pred.keys():
    s=pred[i][:10].replace('-','.')
    s_d=s.split('.')
    pred[i]=f"{s_d[2]}.{s_d[1]}.{s_d[0]}"

In [101]:
pred.pop('test_14 (1)')

'11.01.2020'

In [102]:
pred

{'test_37': '01.01.2020',
 'test_23': '16.01.2020',
 'test_1': '06.01.2020',
 'test_22': '04.01.2020',
 'test_36': '02.01.2020',
 'test_20': '09.01.2020',
 'test_34': '06.01.2020',
 'test_2': '24.01.2020',
 'test_3': '01.01.2020',
 'test_35': '01.01.2020',
 'test_21': '12.01.2020',
 'test_25': '06.01.2020',
 'test_31': '01.01.2020',
 'test_19': '30.01.2020',
 'test_7': '01.01.2020',
 'test_6': '25.01.2020',
 'test_18': '11.02.2020',
 'test_30': '04.01.2020',
 'test_24': '03.01.2020',
 'test_32': '06.01.2020',
 'test_26': '11.01.2020',
 'test_4': '15.02.2020',
 'test_5': '02.01.2020',
 'test_27': '26.01.2020',
 'test_33': '31.01.2020',
 'test_40': '01.01.2020',
 'test_16': '02.01.2020',
 'test_8': '04.01.2020',
 'test_9': '04.01.2020',
 'test_17': '12.01.2020',
 'test_29': '20.01.2020',
 'test_15': '01.01.2020',
 'test_14': '11.01.2020',
 'test_10': '05.01.2020',
 'test_38': '01.01.2020',
 'test_39': '05.01.2020',
 'test_11': '01.01.2020',
 'test_13': '27.01.2020'}

In [85]:
df = pd.DataFrame(list(pred.items()), columns = ['case','symptom_onset'])

In [89]:
df.head(100)

       case symptom_onset
0   test_37    01.01.2020
1   test_23    16.01.2020
2    test_1    06.01.2020
3   test_22    04.01.2020
4   test_36    02.01.2020
5   test_20    09.01.2020
6   test_34    06.01.2020
7    test_2    24.01.2020
8    test_3    01.01.2020
9   test_35    01.01.2020
10  test_21    12.01.2020
11  test_25    06.01.2020
12  test_31    01.01.2020
13  test_19    30.01.2020
14   test_7    01.01.2020
15   test_6    25.01.2020
16  test_18    11.02.2020
17  test_30    04.01.2020
18  test_24    03.01.2020
19  test_32    06.01.2020
20  test_26    11.01.2020
21   test_4    15.02.2020
22   test_5    02.01.2020
23  test_27    26.01.2020
24  test_33    31.01.2020
25  test_40    01.01.2020
26  test_16    02.01.2020
27   test_8    04.01.2020
28   test_9    04.01.2020
29  test_17    12.01.2020
30  test_29    20.01.2020
31  test_15    01.01.2020
32  test_14    11.01.2020
33  test_10    05.01.2020
34  test_38    01.01.2020
35  test_39    05.01.2020
36  test_11    01.01.2020
37  test_13    27.01.2020

In [94]:
df.to_csv('submission.csv',index=False)

In [90]:
submission_ex.head(10)

     case symptom_onset
0  test_1      3.2.2020
1  test_1      6.2.2020
2  test_2      4.2.2020
3  test_3      5.2.2020
4  test_3      6.2.2020
5  test_4      7.2.2020
6  test_4     23.2.2020
7  test_5      8.2.2020
8  test_6      9.2.2020
9  test_7     10.2.2020

In [75]:
submission_ex.info()
print(type(submission_ex['symptom_onset'][0]))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   case           49 non-null     object
 1   symptom_onset  49 non-null     object
dtypes: object(2)
memory usage: 912.0+ bytes
<class 'str'>