In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
%cd /content/gdrive/MyDrive/collab/tumai/newanalysis

/content/gdrive/MyDrive/collab/tumai/newanalysis

In [ ]:
ls

 A0KX894_hr.csv
 A0L9BM2_hr.csv
 A0N9NV4_hr.csv
 A0NVTRV_hr.csv
 A0VFT1N_hr.csv
 A1K5DRI_hr.csv
 A2D7K4A_hr.csv
 A4E0D03_hr.csv
 AAXAA7Z_hr.csv
 AKXN5ZZ_hr.csv
 analysis_sick_person_A4E0D03_hr.ipynb
'Copy of analysis_sick_person_Akxn5ZZ_hr.ipynb'
'Copy of Copy of analysis_sick_person_AAXAA7Z_hr.ipynb'
 data_treated_A0KX894_quality_0.871367814362184.csv
 data_treated_A0N9NV4_quality_0.8315445065359504.csv
 data_treated_A4E0D03_quality_0.662608422280227_10000khz.csv
 data_treated_AAXAA7Z_quality_0.9017821078686461_10000khz.csv
 data_treated_AKXN5ZZ_quality_0.8271026088591573_10000khz.csv
 Godscript.ipynb
 labelsxlsx.xlsx
 notebook_autoanalysis_not_coronaindiv.ipynb
 preprocessed_signal.csv

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("data_treated_AKXN5ZZ_quality_0.8271026088591573_10000khz.csv")

In [ ]:
data

,Unnamed: 0,ECG_Raw,ECG_Clean,ECG_Rate,ECG_Quality,ECG_R_Peaks,datetime,user
0,0,70,-0.336810,80.156493,0.933049,0,2027-12-01 00:00:02,AKXN5ZZ
1,1,69,-0.252058,80.156493,0.933049,0,2027-12-01 00:00:07,AKXN5ZZ
2,2,69,-0.167307,80.156493,0.933049,0,2027-12-01 00:00:22,AKXN5ZZ
3,3,71,-0.082557,80.156493,0.933049,0,2027-12-01 00:00:27,AKXN5ZZ
4,4,72,-0.010309,80.156493,0.933049,0,2027-12-01 00:00:32,AKXN5ZZ
...,...,...,...,...,...,...,...,...
827955,827955,66,5.139819,112.570356,0.796872,0,2028-02-28 23:58:10,AKXN5ZZ
827956,827956,66,4.940949,112.570356,0.796872,0,2028-02-28 23:58:20,AKXN5ZZ
827957,827957,66,4.742176,112.570356,0.796872,0,2028-02-28 23:58:28,AKXN5ZZ
827958,827958,66,4.543469,112.570356,0.796872,0,2028-02-28 23:58:43,AKXN5ZZ
827959,827959,66,4.344796,112.570356,0.796872,0,2028-02-28 23:58:58,AKXN5ZZ

In [ ]:
data = data.drop(columns='Unnamed: 0',axis=1)

In [ ]:
df_labels=pd.read_excel('labelsxlsx.xlsx',sheet_name='SuppTable3_Fig2a_COVID-19',skiprows=3)

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
user=data["user"][0]

In [ ]:
df_labels

,ParticipantID,Category,Symptom_dates,covid_diagnosis_dates,recovery_dates
0,AFPB8J2,COVID-19,[Timestamp('2026-07-14 00:00:00')],[Timestamp('2026-07-17 00:00:00')],[Timestamp('2026-08-06 00:00:00')]
1,APGIB2T,COVID-19,[Timestamp('2023-05-22 00:00:00')],[Timestamp('2023-05-28 00:00:00')],[Timestamp('2023-06-11 00:00:00')]
2,A0KX894,Other Illness,[NaT],[NaT],[NaT]
3,AQC0L71,COVID-19,[Timestamp('2028-06-17 00:00:00')],[Timestamp('2028-06-19 00:00:00')],"[Timestamp('2028-05-16 00:00:00'), Timestamp('..."
4,A0NVTRV,COVID-19,[Timestamp('2023-12-06 00:00:00')],[Timestamp('2023-12-11 00:00:00')],"[Timestamp('2023-12-14 00:00:00'), Timestamp('..."
5,AOYM4KG,COVID-19,"[Timestamp('2023-08-29 00:00:00'), Timestamp('...",[Timestamp('2023-09-18 00:00:00')],"[Timestamp('2023-09-19 00:00:00'), Timestamp('..."
6,AR4FPCC,Other Illness,"[Timestamp('2027-04-11 00:00:00'), Timestamp('...",[NaT],"[Timestamp('2027-05-01 00:00:00'), Timestamp('..."
7,A4G0044,COVID-19,[Timestamp('2027-03-04 00:00:00')],[Timestamp('2027-03-08 00:00:00')],"[Timestamp('2027-03-30 00:00:00'), Timestamp('..."
8,AUILKHG,Other Illness,[Timestamp('2027-07-18 00:00:00')],[NaT],[NaT]
9,AD77K91,Other Illness,[Timestamp('2023-09-04 00:00:00')],[NaT],"[Timestamp('2023-09-14 00:00:00'), Timestamp('..."
10,A3OU183,COVID-19,[Timestamp('2024-11-23 00:00:00')],[Timestamp('2024-11-27 00:00:00')],"[Timestamp('2024-12-09 00:00:00'), Timestamp('..."
11,AX6281V,COVID-19,"[Timestamp('2024-02-08 00:00:00'), Timestamp('...","[Timestamp('2024-04-20 00:00:00'), Timestamp('...","[Timestamp('2024-01-21 00:00:00'), Timestamp('..."
12,A4E0D03,COVID-19,"[Timestamp('2028-03-13 00:00:00'), Timestamp('...",[Timestamp('2028-05-18 00:00:00')],"[Timestamp('2028-06-14 00:00:00'), Timestamp('..."
13,AS2MVDL,COVID-19,[Timestamp('2025-03-02 00:00:00')],[Timestamp('2025-03-05 00:00:00')],[Timestamp('2025-03-25 00:00:00')]
14,AKXN5ZZ,COVID-19,[Timestamp('2028-01-16 00:00:00')],[NaT],"[Timestamp('2028-01-20 00:00:00'), Timestamp('..."
15,AF3J1YC,Other Illness (Influenza B),"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[NaT],"[Timestamp('2025-09-10 00:00:00'), Timestamp('..."
16,AJWW3IY,COVID-19,[Timestamp('2024-08-09 00:00:00')],[Timestamp('2024-08-10 00:00:00')],"[Timestamp('2024-08-15 00:00:00'), Timestamp('..."
17,AAXAA7Z,COVID-19,[Timestamp('2023-03-30 00:00:00')],[Timestamp('2023-04-13 00:00:00')],[Timestamp('2023-05-19 00:00:00')]
18,AHYIJDV,COVID-19,[Timestamp('2025-01-16 00:00:00')],[Timestamp('2025-01-22 00:00:00')],"[Timestamp('2025-01-24 00:00:00'), Timestamp('..."
19,AURCTAK,COVID-19,[NaT],[Timestamp('2025-03-06 00:00:00')],[Timestamp('2025-03-08 00:00:00')]
20,AV2GF3B,COVID-19,[Timestamp('2026-02-12 00:00:00')],[Timestamp('2026-02-18 00:00:00')],[Timestamp('2026-03-22 00:00:00')]
21,AJ7TSV9,COVID-19,[Timestamp('2025-01-28 00:00:00')],[NaT],[NaT]
22,A1K5DRI,COVID-19,"[Timestamp('2028-01-21 00:00:00'), Timestamp('...",[Timestamp('2028-06-21 00:00:00')],"[Timestamp('2028-01-26 00:00:00'), Timestamp('..."
23,A7EM0B6,COVID-19,"[Timestamp('2023-12-26 00:00:00'), Timestamp('...","[Timestamp('2023-12-26 00:00:00'), Timestamp('...","[Timestamp('2024-01-08 00:00:00'), Timestamp('..."
24,ASFODQR,COVID-19,[Timestamp('2024-08-14 00:00:00')],[Timestamp('2024-08-15 00:00:00')],[Timestamp('2024-08-18 00:00:00')]
25,ATHKM6V,COVID-19,[Timestamp('2024-03-06 00:00:00')],[Timestamp('2024-03-06 00:00:00')],[NaT]
26,A0VFT1N,COVID-19,[Timestamp('2023-10-13 00:00:00')],[Timestamp('2023-10-16 00:00:00')],[Timestamp('2023-10-26 00:00:00')]
27,AZIK4ZA,COVID-19,"[Timestamp('2024-07-29 00:00:00'), Timestamp('...",[Timestamp('2024-12-01 00:00:00')],"[Timestamp('2024-10-15 00:00:00'), Timestamp('..."
28,AXI1PBS,Other Illness,"[Timestamp('2026-02-05 00:00:00'), Timestamp('...",[NaT],[Timestamp('2026-05-18 00:00:00')]
29,AYWIEKR,COVID-19,[Timestamp('2023-04-07 00:00:00')],[Timestamp('2023-04-09 00:00:00')],[Timestamp('2023-04-18 00:00:00')]
30,AUY8KYW,COVID-19,[NaT],[Timestamp('2024-03-18 00:00:00')],[NaT]
31,A36HR6Y,COVID-19,"[Timestamp('2023-05-18 00:00:00'), Timestamp('...",[Timestamp('2023-04-16 00:00:00')],[Timestamp('2023-06-10 00:00:00')]
32,AYEFCWQ,COVID-19,"[Timestamp('2025-07-07 00:00:00'), Timestamp('...",[Timestamp('2025-07-08 00:00:00')],[Timestamp('2025-07-08 00:00:00')]
33,AA2KP1S,COVID-19,[Timestamp('2025-01-06 00:00:00')],[Timestamp('2025-01-11 00:00:00')],[NaT]
34,AIFDJZB,COVID-19,[Timestamp('2023-11-07 00:00:00')],[Timestamp('2023-12-20 00:00:00')],[NaT]
35,AJMQUVV,COVID-19,[Timestamp('2024-09-05 00:00:00')],[Timestamp('2024-09-06 00:00:00')],[Timestamp('2024-09-21 00:00:00')]
36,AMV7EQF,COVID-19,[Timestamp('2027-06-09 00:00:00')],[Timestamp('2027-06-11 00:00:00')],[NaT]
37,A1ZJ41O,COVID-19,[Timestamp('2027-08-06 00:00:00')],"[Timestamp('2027-08-10 00:00:00'), Timestamp('...","[Timestamp('2027-08-14 00:00:00'), Timestamp('..."
38,AK7YRBU,Other Illness,[Timestamp('2025-04-12 00:00:00')],[NaT],[NaT]
39,A35BJNV,Other Illness,[Timestamp('2026-08-24 00:00:00')],[NaT],[NaT]
40,AEOBCFJ,Other Illness,[Timestamp('2029-01-11 00:00:00')],[NaT],[NaT]
41,AOGFRXL,Other Illness,[Timestamp('2028-08-19 00:00:00')],[NaT],[NaT]
42,ALKAXMZ,Other Illness,[Timestamp('2024-10-01 00:00:00')],[NaT],[NaT]
43,AA0HAI1_Illness_1,Other Illness,[Timestamp('2029-08-04 00:00:00')],[NaT],[NaT]
44,AA0HAI1_Illness_2,Other Illness,[Timestamp('2029-09-09 00:00:00')],[NaT],[NaT]
45,AA0HAI1_Illness_3,Other Illness,[Timestamp('2030-08-04 00:00:00')],[NaT],[NaT]
46,AFHOHOM,Other Illness,[Timestamp('2027-01-17 00:00:00')],[NaT],[NaT]

In [ ]:
date = df_labels.loc[df_labels.ParticipantID==user,'Symptom_dates']
date= date.iloc[0]

In [ ]:
data["Symptom_dates"]=date.split(" ")[0].split("'")[1]

In [ ]:
data.head()

,ECG_Raw,ECG_Clean,ECG_Rate,ECG_Quality,ECG_R_Peaks,datetime,user,Symptom_dates
0,70,-0.336810,80.156493,0.933049,0,2027-12-01 00:00:02,AKXN5ZZ,2028-01-16
1,69,-0.252058,80.156493,0.933049,0,2027-12-01 00:00:07,AKXN5ZZ,2028-01-16
2,69,-0.167307,80.156493,0.933049,0,2027-12-01 00:00:22,AKXN5ZZ,2028-01-16
3,71,-0.082557,80.156493,0.933049,0,2027-12-01 00:00:27,AKXN5ZZ,2028-01-16
4,72,-0.010309,80.156493,0.933049,0,2027-12-01 00:00:32,AKXN5ZZ,2028-01-16